apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "nginx-service"
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: "nginx-selector"
  type: LoadBalancer    