replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: supermedicalchain/fake-service-backend
  tag: ${TAG}
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: fake-backend
services:
  apiPrefix: ${API_PREFIX}
  tokenSecret: ${TOKEN_SECRET}
  serviceCode: ${SERVICE_CODE}
  gatewayURL: ${GATEWAY_URL}
